import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  body: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 60,
  },
  loading: {
    color: '#555',
    textAlign: 'center',
    marginTop: 100,
  },
  congratsText: {
    color: '#4CAF50',
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  topItem: {
    alignItems: 'center',
  },
  topLabel: {
    color: '#ccc',
    fontSize: 15,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  topValue: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '600',
    marginTop: 2,
  },
  timerSection: {
    alignItems: 'center',
    marginTop: 40,
  },
  timerRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  timer: {
    color: '#fff',
    fontSize: 80,
    fontWeight: '200',
    fontVariant: ['tabular-nums'],
  },
  timerUnit: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '200',
    marginHorizontal: 6,
    marginBottom: 2,
  },
  phase: {
    color: '#FF9800',
    fontSize: 24,
    fontWeight: '600',
    marginTop: 10,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  milestones: {
    marginTop: 28,
    marginBottom: 24,
    gap: 10,
  },
  milestoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  milestoneHours: {
    color: '#bbb',
    fontSize: 17,
    fontWeight: '600',
    width: 38,
    textAlign: 'right',
  },
  milestoneLabel: {
    color: '#bbb',
    fontSize: 17,
  },
  milestoneActive: {
    color: '#FF9800',
    fontWeight: '700',
  },
  milestoneFireIcon: {
    fontSize: 16,
  },
  milestoneReached: {
    color: '#4CAF50',
  },
  button: {
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 10,
  },
  buttonPressed: {
    backgroundColor: '#111',
    borderColor: '#666',
  },
  buttonText: {
    color: '#ddd',
    fontSize: 16,
  },
  tutorialOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  tutorialOverlayLight: {
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  tutorialBox: {
    paddingHorizontal: 32,
    alignItems: 'center',
  },
  tutorialBoxBordered: {
    borderWidth: 1,
    borderColor: '#fff',
    borderRadius: 12,
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingVertical: 20,
    marginHorizontal: 8,
  },
  tutorialTextFirst: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 12,
  },
  tutorialText: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 8,
  },
  tutorialDismiss: {
    color: '#666',
    fontSize: 13,
    marginTop: 12,
  },
  menuIndicator: {
    zIndex: 101,
    paddingVertical: 8,
  },
  menuIndicatorText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  tabBar: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#1a1a1a',
    paddingVertical: 10,
    paddingBottom: 20,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
  },
  tabIcon: {
    fontSize: 22,
    color: '#777',
  },
  tabLabel: {
    fontSize: 11,
    color: '#777',
    marginTop: 2,
  },
  tabActive: {
    color: '#fff',
  },
  tabContent: {
    flex: 1,
  },
  sectionTitle: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 14,
  },
  emptyText: {
    color: '#666',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 40,
  },
  historyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#1a1a1a',
  },
  historyDate: {
    color: '#ccc',
    fontSize: 15,
  },
  historyDuration: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
  },
  historyStatus: {
    fontSize: 13,
    marginTop: 4,
  },
  historyReached: {
    color: '#4CAF50',
  },
  historyNotReached: {
    color: '#999',
  },
  historyDim: {
    color: '#999',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 24,
  },
  statsRowItem: {
    alignItems: 'center',
  },
  statsRowValue: {
    color: '#fff',
    fontSize: 19,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
  },
  statsRowLabel: {
    color: '#aaa',
    fontSize: 12,
    marginTop: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  settingsLabel: {
    color: '#ccc',
    fontSize: 14,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 12,
  },
  goalOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  goalOption: {
    borderWidth: 1,
    borderColor: '#333',
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 18,
  },
  goalOptionActive: {
    borderColor: '#4CAF50',
    backgroundColor: '#1a2e1a',
  },
  goalOptionText: {
    color: '#ccc',
    fontSize: 16,
  },
  goalOptionTextActive: {
    color: '#4CAF50',
  },
  settingsDivider: {
    height: 1,
    backgroundColor: '#1a1a1a',
    marginVertical: 16,
  },
  settingsInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#1a1a1a',
  },
  settingsInfoLabel: {
    color: '#ccc',
    fontSize: 16,
  },
  settingsInfoValue: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  settingsToggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  settingsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#1a1a1a',
  },
  settingsRowText: {
    color: '#ccc',
    fontSize: 16,
  },
  settingsRowArrow: {
    color: '#777',
    fontSize: 22,
  },
  settingsRowSub: {
    color: '#888',
    fontSize: 12,
    marginTop: 2,
  },
  versionText: {
    color: '#444',
    fontSize: 13,
    textAlign: 'center',
    marginTop: 32,
    marginBottom: 40,
  },
  howToStep: {
    color: '#ccc',
    fontSize: 15,
    lineHeight: 24,
  },
  comparisonRow: {
    flexDirection: 'row',
    gap: 12,
  },
  comparisonColumn: {
    flex: 1,
  },
  comparisonHeader: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  comparisonHeaderPro: {
    color: '#4CAF50',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  comparisonItem: {
    color: '#999',
    fontSize: 14,
    lineHeight: 22,
  },
  comparisonItemPro: {
    color: '#ccc',
    fontSize: 14,
    lineHeight: 22,
  },
  adLink: {
    alignItems: 'center',
    paddingVertical: 6,
  },
  adLinkText: {
    color: '#888',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
  },
  chartOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 8,
  },
  chartPopup: {
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#333',
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
    minWidth: 160,
  },
  chartPopupTime: {
    color: '#fff',
    fontSize: 15,
    fontVariant: ['tabular-nums'] as any,
  },
  chartPopupArrow: {
    color: '#555',
    fontSize: 14,
    marginVertical: 2,
  },
  chartPopupDuration: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '600',
    fontVariant: ['tabular-nums'] as any,
    marginBottom: 4,
  },
  chartPopupStatus: {
    fontSize: 13,
    fontWeight: '600',
  },
  upgradeBlock: {
    borderWidth: 1,
    borderColor: '#333',
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 20,
  },
  upgradeText: {
    color: '#aaa',
    fontSize: 15,
  },
  proDisabledLabel: {
    color: '#555',
  },
  proDisabledInput: {
    opacity: 0.4,
  },
  customInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  customInput: {
    flex: 1,
    backgroundColor: '#1a1a1a',
    borderRadius: 6,
    color: '#fff',
    fontSize: 15,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#333',
  },
  customHHMMInput: {
    width: 48,
    backgroundColor: '#1a1a1a',
    borderRadius: 6,
    color: '#fff',
    fontSize: 15,
    textAlign: 'center',
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#333',
  },
  customHHMMLabel: {
    color: '#999',
    fontSize: 14,
    alignSelf: 'center',
  },
  customClearBtn: {
    backgroundColor: '#2a1a1a',
    borderRadius: 6,
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  customClearBtnText: {
    color: '#e53935',
    fontSize: 14,
    fontWeight: '600',
  },
  customInputBtn: {
    backgroundColor: '#1a2e1a',
    borderRadius: 6,
    paddingHorizontal: 16,
    justifyContent: 'center',
  },
  customInputBtnText: {
    color: '#4CAF50',
    fontSize: 15,
    fontWeight: '600',
  },
  historyNote: {
    color: '#999',
    fontSize: 13,
    marginTop: 4,
  },
  editButton: {
    backgroundColor: '#1a2e1a',
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 14,
    marginTop: 6,
  },
  editButtonText: {
    color: '#4CAF50',
    fontSize: 13,
    fontWeight: '600',
  },
  historyPhoto: {
    width: 40,
    height: 40,
    borderRadius: 4,
    marginTop: 6,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  modalContent: {
    backgroundColor: '#111',
    borderRadius: 10,
    padding: 20,
  },
  modalTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 16,
  },
  modalLabel: {
    color: '#fff',
    fontSize: 13,
    marginBottom: 6,
    marginTop: 12,
  },
  modalDisabled: {
    color: '#555',
  },
  modalInput: {
    backgroundColor: '#1a1a1a',
    borderRadius: 6,
    color: '#fff',
    fontSize: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#fff',
  },
  modalInputDisabled: {
    opacity: 0.4,
  },
  modalPhotoPreview: {
    width: 80,
    height: 80,
    borderRadius: 6,
    marginTop: 4,
  },
  modalPhotoButton: {
    borderWidth: 1,
    borderColor: '#fff',
    borderRadius: 6,
    paddingVertical: 10,
    alignItems: 'center' as const,
  },
  modalPhotoButtonText: {
    color: '#fff',
    fontSize: 14,
  },
  modalButtons: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
    marginTop: 20,
  },
  modalDelete: {
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  modalDeleteText: {
    color: '#ff4444',
    fontSize: 14,
  },
  modalCancel: {
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  modalCancelText: {
    color: '#888',
    fontSize: 15,
  },
  modalConfirm: {
    backgroundColor: '#1a2e1a',
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  modalConfirmText: {
    color: '#4CAF50',
    fontSize: 15,
    fontWeight: '600',
  },
});
